// AUTO-GENERATED by build.js from /_redirects. Do not edit by hand.
// Regenerated on every `npm run build`. 336 rules.

const RULES = [
  {
    "prefix": null,
    "exact": "/individual",
    "target": "/individuals/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/our-product",
    "target": "/individuals/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academies-paths",
    "target": "/academies/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/employer-sponsorship",
    "target": "/individuals/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/terms-of-service",
    "target": "/terms-of-service",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/cpe-cpd-training",
    "target": "/individuals/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/pricing",
    "target": "/pricing",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/blog",
    "target": "/blog",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/individual/blogs/",
    "exact": null,
    "target": "/blog/:splat",
    "hasSplat": true,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/advanced-excel",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/advanced-power-bi-concepts",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/ai-for-business-professionals",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/building-apps-in-power-apps",
    "target": "/courses/power-apps",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/building-dashboards-in-power-bi",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/financial-modelling",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/introduction-to-financial-models-and-valuation",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/mastering-alteryx",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/mastering-excel-for-beginners",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/mastering-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/microsoft-word",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/presentations-in-powerpoint",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/project-management-fundamentals",
    "target": "/academies/project-management",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/rpa-with-power-automate",
    "target": "/courses/rpa-power-automate",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/sql-fundamentals",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/paths/the-fundamentals-of-machine-learning-in-python",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/individual/paths/",
    "exact": null,
    "target": "/academies/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/advanced-data-visualization-for-finance",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/associate-data-analyst",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/associate-management-consultant",
    "target": "/industries/management-consulting",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/data-analyst",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/data-for-finance-and-accounting",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/data-wrangler",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/early-career-acceleration",
    "target": "/specialist-programs/graduate-program",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/individual/academy/financial-modelling-and-statistics",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/individual/academy/",
    "exact": null,
    "target": "/academies/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/individual/",
    "exact": null,
    "target": "/individuals/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/adaptive-project-management",
    "target": "/courses/adaptive-project-management",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/ai-fundamentals",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/alteryx",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/alteryx-intelligence-suite",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/apis",
    "target": "/courses/apis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/app-development-fundamentals",
    "target": "/courses/app-development-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/business-analysis",
    "target": "/courses/business-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-ethics-risk",
    "target": "/courses/data-ethics-risk",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-literacy",
    "target": "/courses/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-presentation-skills",
    "target": "/courses/data-presentation-skills",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-regulation",
    "target": "/courses/data-regulation",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-security",
    "target": "/courses/data-security",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-strategy-governance",
    "target": "/courses/data-strategy-governance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/data-visualization",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/excel",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/finance-fundamentals",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/financial-modeling",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/machine-learning-with-python",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/microsoft-teams",
    "target": "/courses/microsoft-teams",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/outlook",
    "target": "/courses/outlook",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/power-apps",
    "target": "/courses/power-apps",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/power-bi",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/powerpoint",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/project-management-fundamentals",
    "target": "/courses/project-management-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/python-fundamentals",
    "target": "/courses/python-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/rpa-fundamentals",
    "target": "/courses/rpa-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/rpa-with-power-automate",
    "target": "/courses/rpa-power-automate",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/rpa-with-uipath",
    "target": "/courses/rpa-uipath",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/sharepoint",
    "target": "/courses/sharepoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/sql",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/statistical-analysis",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/strategic-analysis",
    "target": "/courses/strategic-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/technology-fundamentals",
    "target": "/courses/technology-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject/word",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/subject/",
    "exact": null,
    "target": "/courses/:splat",
    "hasSplat": true,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subject",
    "target": "/courses",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subjects",
    "target": "/courses",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/subjects-library",
    "target": "/catalog",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/formulas-and-functions",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/pivot-tables",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-excel-macros",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/applications-and-macros",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/macros-add-ins-and-mail-merge",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/lookups-and-database-functions",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/text-time-and-dates",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/finding-and-replacing-data",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introducing-power-pivot",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/power-query",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/the-query-editor",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/finance-functions",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/understanding-sql-databases",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/selecting-and-filtering-data-with-sql",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/joining-data-with-sql",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/aggregating-data-with-sql",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/data-manipulation-with-sql",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/finance-functions-in-sql",
    "target": "/courses/sql",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/exploring-power-bi-visualizations",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/connecting-to-different-data-sources",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/connecting-to-live-data",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/the-power-bi-online-service",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/power-bi-online-service",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/power-bi-case-study",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/build-your-first-dashboard",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/building-your-first-dashboard",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-dax",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/practical-applications-of-dax",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-dax-functions-and-concepts",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-dax-function-and-concepts",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/optimizing-for-performance",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/developing-and-visualizing-your-data-model",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/designing-effective-dashboards",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introducing-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/creating-visualizations-in-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-formulas-in-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/further-formulas-in-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/filter-groups-and-sets",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/level-of-detail-expressions",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/cleaning-data-with-tableau-prep",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/reshaping-data-in-tableau-prep",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-visualizations-in-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-data-connections",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/adding-interactivity",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/spatial-data-and-mapping",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/alteryx-fundamentals",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/inputting-and-outputting-data",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/joining-and-transforming-data",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/applying-parsing-and-formula-tools",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/data-preparation",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-data-preparation",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/computer-vision",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/text-mining",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/clustering-and-market-basket-analysis",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-clustering",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-classification",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/classification-models",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/regression-analysis",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-regression",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/identifying-patterns",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/time-series-analysis",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/predicting-future-values",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/predicting-scenarios",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/python-fundamentals",
    "target": "/courses/python-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/functions-conditionality-and-loops",
    "target": "/courses/python-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/web-scraping",
    "target": "/courses/python-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/working-with-apis",
    "target": "/courses/apis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/the-api-economy",
    "target": "/courses/apis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/regression-analysis-in-python",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/decision-trees-in-python",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/k-means-clustering-in-python",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/feature-engineering",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-predictive-modeling",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/developing-ai-models",
    "target": "/courses/machine-learning-python",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-artificial-intelligence",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/business-applications-of-ai",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/exploring-chatgpt",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-generative-ai",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/large-language-models",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/understanding-natural-language",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-prompt-engineering",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-prompt-concepts",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-retrieval-augmented-generation-rag",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/using-copilot-in-microsoft-365",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/data-analytics-for-chatgpt-and-copilot",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-copilot-studio",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-the-eu-artificial-intelligence-act",
    "target": "/courses/data-regulation",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/generative-ai-and-chatgpt",
    "target": "/courses/ai-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-robotic-process-automation",
    "target": "/courses/rpa-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/uipath-basics",
    "target": "/courses/rpa-uipath",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/automating-ui-interactions-with-uipath",
    "target": "/courses/rpa-uipath",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-uipath-workflows",
    "target": "/courses/rpa-uipath",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-power-automate",
    "target": "/courses/rpa-power-automate",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/creating-power-automate-flows",
    "target": "/courses/rpa-power-automate",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-power-automate-flows",
    "target": "/courses/rpa-power-automate",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-power-apps",
    "target": "/courses/power-apps",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/building-a-canvas-app",
    "target": "/courses/power-apps",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/creating-a-model-driven-app",
    "target": "/courses/power-apps",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/dataverse-for-power-apps",
    "target": "/courses/power-apps",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-finance",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-financial-statements",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/building-financial-statements",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/preparing-financial-statements",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/automating-financial-statement-preparation",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/analyzing-the-income-statement",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/analyzing-balance-sheets-and-the-cash-flow-statement",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/financial-ratios",
    "target": "/courses/finance-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/build-your-first-model",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/financial-projections",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/forward-looking-models",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/leveraged-buyouts",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-lbo-modeling-part-1",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/advanced-lbo-modeling-part-2",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-valuation",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/performing-your-first-company-valuation",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/valuing-a-real-estate-investment",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/modeling-startup-investments",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/mergers-and-acquisitions",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/monte-carlo-simulation",
    "target": "/courses/financial-modeling",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introducing-statistics",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/principles-of-statistics",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/probability-principles",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/probability-distributions",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/hypothesis-testing",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/ab-testing",
    "target": "/courses/statistical-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-data-literacy",
    "target": "/courses/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/thinking-and-communicating-with-data",
    "target": "/courses/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/communicating-data-effectively",
    "target": "/courses/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/visual-data-thinking",
    "target": "/courses/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/applying-visual-data-skills",
    "target": "/courses/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-visualizations",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/visualization-in-practice",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/chart-construction",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/chart-selection",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/charts-in-depth",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/improving-your-visualizations",
    "target": "/courses/visualization-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/dashboard-design",
    "target": "/courses/data-presentation-skills",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/presenting-your-data",
    "target": "/courses/data-presentation-skills",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/presentation-design",
    "target": "/courses/data-presentation-skills",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/presentation-visuals",
    "target": "/courses/data-presentation-skills",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/telling-stories-with-data",
    "target": "/courses/data-presentation-skills",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/building-a-data-driven-culture",
    "target": "/courses/data-strategy-governance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/defining-your-data-strategy",
    "target": "/courses/data-strategy-governance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/planning-a-data-driven-project",
    "target": "/courses/data-strategy-governance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/planning-a-research-project",
    "target": "/courses/strategic-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/research-in-business",
    "target": "/courses/strategic-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/internal-and-external-analysis",
    "target": "/courses/strategic-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/positioning-and-process-analysis",
    "target": "/courses/strategic-analysis",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/applying-ethical-thinking",
    "target": "/courses/data-ethics-risk",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-data-ethics",
    "target": "/courses/data-ethics-risk",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/introduction-to-gdpr",
    "target": "/courses/data-regulation",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/handling-data-securely-and-responsibly",
    "target": "/courses/data-security",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/keeping-your-information-safe",
    "target": "/courses/data-security",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/typing-and-formatting-text-in-word",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/adjusting-the-layout-of-the-document",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/adding-bullet-points-and-tables",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/adding-references",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/reviewing-sharing",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/template-customization",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/data-manipulation-and-formatting",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/powerpoint-fundamentals",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/presenting-in-powerpoint",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/designing-with-shapes-pictures-and-themes",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/sending-and-organizing-emails",
    "target": "/courses/outlook",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/managing-contacts-calendars-and-tasks",
    "target": "/courses/outlook",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/foundational-technologies",
    "target": "/courses/technology-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/established-technologies",
    "target": "/courses/technology-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/emerging-technologies",
    "target": "/courses/technology-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/frontier-technologies",
    "target": "/courses/technology-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/app-development-fundamentals",
    "target": "/courses/app-development-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/storing-transforming-and-visualizing-data",
    "target": "/courses/app-development-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/course/getting-started-with-projects",
    "target": "/courses/project-management-fundamentals",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/course/",
    "exact": null,
    "target": "/courses",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/foundations-of-artificial-intelligence",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/foundations-of-generative-ai",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/principles-of-generative-ai",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/ai-fundamentals",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/getting-started-with-ai",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/ai-ml-with-python",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/ai-predictions-and-patterns-in-machine-learning",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/essential-principles-of-data-analysis",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/communicating-and-visualizing-data",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/data-analysis-with-excel-essentials",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/data-analysis-with-excel-analysis",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/data-preparation-with-alteryx",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/data-preparation-with-python",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/data-preparation-with-sql",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/getting-started-with-data-in-alteryx",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-data-with-alteryx",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-data-with-tableau",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/predictive-analytics-with-alteryx",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/visualizing-data-with-excel",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/visualizing-data-with-power-bi",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/visualizing-data-with-power-bi-the-query-editor-and-dax",
    "target": "/courses/power-bi",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/visualizing-data-with-tableau",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/computer-vision-with-alteryx-intelligence-suite",
    "target": "/courses/alteryx-intelligence-suite",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/financial-modeling-with-excel-essentials",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/financial-modeling-with-excel-advanced",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/modeling-for-business",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/understanding-financial-data-with-excel",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/core-project-management-skills",
    "target": "/academies/project-management",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/alteryx-designer-core-certification-preparation",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-for-the-alteryx-designer-core-exam",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-for-core-micro-credential-data-manipulation-and-transformation",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-for-core-micro-credential-data-transformation",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-for-core-micro-credential-general-knowledge",
    "target": "/courses/alteryx",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/preparing-for-the-tableau-desktop-specialist-exam",
    "target": "/courses/tableau",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/microsoft-excel-associate",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/microsoft-powerpoint-associate",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/microsoft-word-associate",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/applied-excel-tools-macros-vba",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/applied-excel-tools-power-pivot-and-power-query-essentials",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/presenting-business-data-with-powerpoint",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/presenting-data-with-powerpoint",
    "target": "/courses/powerpoint",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/presenting-data-with-word",
    "target": "/courses/word",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/robotic-process-automation-with-power-automate",
    "target": "/courses/rpa-power-automate",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/path/robotic-process-automation-with-uipath",
    "target": "/courses/rpa-uipath",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/path/",
    "exact": null,
    "target": "/academies/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/learning-paths",
    "target": "/academies/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/project/",
    "exact": null,
    "target": "/projects",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/academies/ai-for-business-professionals",
    "target": "/academies/ai",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/academies/associate-analyst",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/academies/data-citizen",
    "target": "/academies/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/specialist-programs/grad-program",
    "target": "/specialist-programs/graduate-program",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/grad-program",
    "target": "/specialist-programs/graduate-program",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/graduate-onboarding-work-readiness",
    "target": "/specialist-programs/graduate-program",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/specialist-programs/early-careers",
    "target": "/specialist-programs/graduate-program",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/specialist-programs/project-management",
    "target": "/academies/project-management",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/specialist-programs/financial-storytelling",
    "target": "/academies/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/industries/government",
    "target": "/industries/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/finance-teams",
    "target": "/industries/corporate-finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/join-for-free",
    "target": "/try-free/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/free-tier",
    "target": "/try-free/",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/try-free-business",
    "target": "/try-free/business",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/teams",
    "target": "/for-business/teams",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/enterprise",
    "target": "/for-business/enterprises",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/for-business/for-enterprises",
    "target": "/for-business/enterprises",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/platform",
    "target": "/for-business/platform",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/integrations",
    "target": "/for-business/integrations",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/custom-programs",
    "target": "/for-business/custom-learning-design",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/case-studies-white-papers",
    "target": "/resources/case-studies",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/corporate-programs/heineken",
    "target": "/resources/case-studies",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": "/corporate-programs/",
    "exact": null,
    "target": "/resources/case-studies",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/webinars",
    "target": "/resources/webinars",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/ai-use-policy",
    "target": "/resources/guides/ai-use-policy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/data-literacy-assessment",
    "target": "/resources/assessments/data-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/ai-literacy-assessment",
    "target": "/resources/assessments/ai-literacy",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/finance-assessment",
    "target": "/resources/assessments/finance",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/project-management-assessment",
    "target": "/resources/assessments/project-management",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/library",
    "target": "/catalog",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/catalog-download",
    "target": "/catalog",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/talk-to-sales",
    "target": "/contact",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/blog/excel",
    "target": "/courses/excel",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/sandbox",
    "target": "/404",
    "hasSplat": false,
    "status": 404
  },
  {
    "prefix": null,
    "exact": "/sandbox-september-2025",
    "target": "/404",
    "hasSplat": false,
    "status": 404
  },
  {
    "prefix": null,
    "exact": "/exclusive-pwc-pilot",
    "target": "/404",
    "hasSplat": false,
    "status": 404
  },
  {
    "prefix": null,
    "exact": "/sp",
    "target": "/404",
    "hasSplat": false,
    "status": 404
  },
  {
    "prefix": null,
    "exact": "/black-friday-60-off-all-access",
    "target": "/404",
    "hasSplat": false,
    "status": 404
  },
  {
    "prefix": null,
    "exact": "/b2b-pricing-calculator-2026",
    "target": "/pricing",
    "hasSplat": false,
    "status": 301
  },
  {
    "prefix": null,
    "exact": "/style-guide",
    "target": "/404",
    "hasSplat": false,
    "status": 404
  },
  {
    "prefix": null,
    "exact": "/search",
    "target": "/catalog",
    "hasSplat": false,
    "status": 301
  }
];

function findMatch(pathname) {
  for (let i = 0; i < RULES.length; i++) {
    const r = RULES[i];
    if (r.exact !== null) {
      if (pathname === r.exact) {
        return { target: r.target, status: r.status };
      }
    } else if (pathname.startsWith(r.prefix)) {
      const splat = pathname.slice(r.prefix.length);
      const target = r.hasSplat ? r.target.replace(/:splat/g, splat) : r.target;
      return { target, status: r.status };
    }
  }
  return null;
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const match = findMatch(url.pathname);
  if (!match) {
    return context.next();
  }

  // 404 / 410: serve the styled 404 page via ASSETS binding so users get the
  // designed error page, but with the intended status code. Crawlers see 404,
  // which is the whole point of these rules.
  if (match.status === 404 || match.status === 410) {
    try {
      const asset = await context.env.ASSETS.fetch(new URL('/404.html', url.origin));
      return new Response(asset.body, {
        status: match.status,
        headers: { 'content-type': 'text/html; charset=utf-8' }
      });
    } catch (e) {
      return new Response('Not Found', { status: match.status });
    }
  }

  // Redirect statuses (301/302/303/307/308). Target may be a path (resolved
  // against current origin) or an absolute URL.
  const destination = match.target.startsWith('http')
    ? match.target
    : new URL(match.target, url.origin).href;
  return Response.redirect(destination, match.status);
}
